### ISSUE TITLE
Incompatible with TF2

### ISSUE THREAD

**Issue by Hoeijmakers** [mirca/lad#6]
I'm not sure if this is still being maintained, but in the python version of LAD there are compatibility issues with tensorflow 2, which no longer uses sessions.

I have tried to implement backward compatibility in `lad.py` as:

`import tensorflow.compat.v1 as tf`
`tf.disable_v2_behavior()`

but further errors with tensorflow are raised, in my case:

`OperatorNotAllowedInGraphError: Iterating over a symbolic tf.Tensor is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.`

I unfortunately have no knowledge about tensorflow so I am unable to remedy this further. In the off chance that you are still maintaining this, it would be great if you could consider updating the code to be TF 2 compatible.

**Comment by mirca** [comment]
hey @Hoeijmakers, thanks for opening this issue. 

sorry, i have no intention of maintaining this.
